name: Rust

on:
  push:
    branches: [ "main", "actions-test" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.version }}
    strategy:
      matrix:
        version: [20.04, 22.04, 24.04, 24.10, 25.04]
    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
      RUSTDOCFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -qy librrd-dev curl build-essential pkg-config libclang-dev
    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Install rust components
      run: rustup component add clippy rustfmt
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Check docs
      run: cargo doc --no-deps
    - name: Run tests
      run: cargo test --verbose
  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:${{ matrix.version }}
    strategy:
      matrix:
        version: [39, 40, 41, 42]
    steps:
    - uses: actions/checkout@v3
    - name: Install development environment
      run: dnf group install -qy --refresh c-development
    - name: Install dependencies
      run: dnf install -qy rrdtool-devel curl clang
    - name: Install rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal -y
    - name: Install rust components
      run: $HOME/.cargo/bin/rustup component add clippy rustfmt
    - name: Check formatting
      run: $HOME/.cargo/bin/cargo fmt --check
    - name: Build
      run: $HOME/.cargo/bin/cargo build --verbose
    - name: Check docs
      run: RUSTDOCFLAGS="-D warnings" $HOME/.cargo/bin/cargo doc --no-deps
    - name: Run tests
      run: $HOME/.cargo/bin/cargo test --verbose
